name: Generate and Publish Documentation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: |
        cd Bank
        dotnet restore
        
    - name: Build project
      run: |
        cd Bank
        dotnet build --no-restore
        
    - name: Install DocFX
      run: dotnet tool install -g docfx
      
    - name: Create DocFX config
      run: |
        mkdir -p docs
        cat > docs/docfx.json << 'EOF'
        {
          "metadata": [
            {
              "src": [
                {
                  "files": [ "**/*.csproj" ],
                  "src": "../Bank"
                }
              ],
              "dest": "api",
              "includePrivateMembers": false,
              "disableGitFeatures": false,
              "disableDefaultFilter": false,
              "noRestore": false,
              "namespaceLayout": "flattened",
              "memberLayout": "samePage"
            }
          ],
          "build": {
            "content": [
              {
                "files": [ "api/**.yml", "api/index.md" ]
              },
              {
                "files": [ "*.md", "toc.yml" ],
                "exclude": [ "**/bin/**", "**/obj/**" ]
              }
            ],
            "resource": [
              {
                "files": [ "images/**" ]
              }
            ],
            "output": "_site",
            "globalMetadataFiles": [],
            "fileMetadataFiles": [],
            "template": [ "default" ],
            "postProcessors": [],
            "keepFileLink": false,
            "disableGitFeatures": false
          }
        }
        EOF
        
    - name: Create index page
      run: |
        cat > docs/index.md << 'EOF'
        # Bank Domain Documentation
        
        Esta es la documentación generada automáticamente para el dominio bancario.
        
        ## Namespaces
        
        - [Bank.Domain](api/Bank.Domain.html)
        
        ## Clases principales
        
        - [Cliente](api/Bank.Domain.Cliente.html) - Representa un cliente del banco
        - [CuentaAhorro](api/Bank.Domain.CuentaAhorro.html) - Representa una cuenta de ahorro
        EOF
        
    - name: Create TOC
      run: |
        cat > docs/toc.yml << 'EOF'
        - name: Home
          href: index.md
        - name: API Documentation
          href: api/
          homepage: api/index.md
        EOF
        
    - name: Generate documentation with docfx
      run: |
        cd docs
        docfx docfx.json --serve
      continue-on-error: true
      
    - name: Build with docfx
      run: |
        cd docs
        docfx build docfx.json
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs/_site'
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4